### PR TITLE
Update to ff13c

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by iabdalkader** [comment]
There's an issue with seek/tell.

**Comment by iabdalkader** [comment]
Actually this bug seems related to our code. I tested file creation, read/write, seek on PYB lite.

EDIT/UPDATE: Sorry there's no bug at all in the updated FF. I was testing an old firmware with ff12b exFAT bug.

**Comment by dpgeorge** [comment]
Thanks for the attempt at this, but unfortunately this patch won't work because it's a single commit.  The idea is to reapply the commits from work-R0.12b that modify the original vendor code, reapplying them on top of R0.13c.  Doing it this way is supposed to help keep the upgrades simple, but in reality it's not that simple because the FatFS code changes a lot from version to version.

So, it needs to be redone, sorry.

I can put aside some time to do this, unless you want to attempt it again.

**Comment by iabdalkader** [comment]
> Doing it this way is supposed to help keep the upgrades simple, but in reality it's not that simple because the FatFS code changes a lot from version to version.

Yes that and I won't be able to compile after each commit (to catch typos, etc..). Anyway, I think I may have time to do this, but wouldn't it be easier to just write those commits as guidelines in the README and use unit-tests to check the upgrade ?

**Comment by dpgeorge** [comment]
> and use unit-tests to check the upgrade

There are already some simple tests in the working branches.

**Comment by dpgeorge** [comment]
FYI I started doing the R0.13c update.

**Comment by dpgeorge** [comment]
I've finished the R0.13c update and pushed a new branch, work-R0.13c.

I've tested it with MicroPython and there seems to be at least one problem: an existing FAT12 filesystem with a file README.txt comes out in the directory listing as README.TXt.

**Comment by iabdalkader** [comment]
Does this happen if you create the FS with the new FatFS ? I don't have this issue and I'm using the same ffconfig except I define MICROPY_FATFS_ENABLE_LFN as 2

**Comment by dpgeorge** [comment]
It looks like a new bug in fatfs: when filenames are stored there is a short (SFN) and possibly long (LFN) name.  LFN is not stored if it can be derived from SFN using simple rules:
- LFN = SFN
- LFN = SFN with main body name changed to lower case
- LFN = SFN with extension changed to lower case
- LFN = SFN with both body and extension changed to lower case
There are flags (NS_BODY and NS_EXT) to say which parts of the SFN should be made lower case, in such a situation.

The new code seems to have a bug in it in the way it converts the case of the letters: SFN is stored always in 8+3 format with spaces to indicate unused chars, eg for README.txt it's "README  EXT" with NS_EXT flag set.  The old code would convert "README  EXT" to SFN of "README.TXT" and LFN of "README.txt" at the same time.  The new code does these conversions in separate loops, and the second loop (converting SFN to LFN) counts 9 chars to tell if it's in the extension or not.  But 9 chars now gets you from "README.TXT" to "README.TXt", instead of "README  TXT" to "README.txt".

**Comment by dpgeorge** [comment]
The relevant function is get_fileinfo().  Looks like the bug was introduced in R0.13a.

**Comment by dpgeorge** [comment]
Bug report posted upstream here: http://elm-chan.org/fsw/ff/bd/?show=3313

**Comment by iabdalkader** [comment]
How can I reproduce this bug ?

**Comment by dpgeorge** [comment]
> How can I reproduce this bug ?

I guess the only sure way to do it would be to create a FAT12 filesystem with the old version, and create a new file called README.txt on it (eg using a pyboard).  Then upgrade to this new version of FatFS, mount the filesystem and list the files.

**Comment by iabdalkader** [comment]
I was able to reproduce the bug with a filesystem created with ff13c. I think this is a known issue, see ff13c_p2.diff here: http://elm-chan.org/fsw/ff/patches.html I applied all 3 patches and I can confirm the issue is fixed.

**Comment by dpgeorge** [comment]
Ok, thanks for the link to those patches.  Indeed it seems like the bug is fixed there.

**Comment by dpgeorge** [comment]
I applied the 3 patches to the work-R0.13c branch.

**Comment by iabdalkader** [comment]
Closing this PR.

**Pull request closed without merging**
