### PR TITLE
Update vendor code to R0.13c

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by iabdalkader** [comment]
@dpgeorge Should I wait for you to merge this first ?

**Comment by dpgeorge** [comment]
Thanks, but I would like to have the full history of versions in the vendor branch, ie upgrade ff13 then ff13b then ff13c.  I wouldn't necessarily port all the patches to these versions, probably just ff13c.

Also, it seems that ff13 renamed the doc dir to documents and src to source.  I think it's fair if this repo keeps them as the original doc and src, at least to give some chance to have the working patches apply cleanly.

Anyway, I'm happy to make the commits myself to update to ff13, ff13b and ff13c.  I have a script to do it so it's easy.

**Comment by iabdalkader** [comment]
Okay I'll close this PR and wait for you to update to ff13c.

**Comment by dpgeorge** [comment]
Ok, now updated.

**Pull request closed without merging**
