### PR TITLE
Add f_repair(FATFS*).

### PR DESCRIPTION
**Pull request by jimmo**
This will:
 - Clear the dirty flag (avoiding the "This volume was not cleanly unmounted" error)
 - Clean up any unreferenced clusters (potentially left behind from conflicting host/device writes).
 - Update file sizes to match cluster chain length. (Or truncate cluster chain to match smaller file size).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Fantastic work, thank you!

Some points:
- please split into 2 commits, one adding the new function to `src/*` and the second adding the tests to `tests/*`
- did you forget to commit `test.full.img`?  this second test won't run without it
- I see that `f_repair()` requires a working buffer, and it looks like it must be dynamically allocated because the size (fatent/8) can vary a lot.  So the size can't really be predetermined and statically allocated (like it's done with `f_mkfs()`, on the stack).  Is this true, is this a fundamental limitation of doing the repair?  In other words, would it be possible, at least in principle, to do a repair with a fixed amount of working space for all possible filesystems?
- with this working buffer, the size is computed as `n_fatent/8` but shouldn't this be rounded up to `(n_fatent + 7) / 8`?  Eg if `n_fatent=123` then the largest cluster is 122 and it'll index the bitmap at position 15, but that's outside the bitmap array bounds 0-14.

**Comment by jimmo** [comment]
Thanks!

1. Will do.
2. Yeah I wanted to create a couple of test images with different cases. Will add them shortly.
3. Yes. Not a problem for most devices that have a small, known flash size, but would be nice to make this work more generally. I think probably the best option is just to make f_repair use whatever size buffer it's given and reduce the precision. i.e. each bit in the bitmap represents `buf_len / n_fatent / 8` clusters. So it will never mistakenly reclaim a used cluster but will occasionally miss some, which is fine. You could use a bloom filter if the number of allocated clusters is below a certain threshold, but this seems unnecessarily complex (and you don't know the true number of allocated clusters until you've done a repair anyway).
4. Yep, good catch. Will fix.

**Comment by dpgeorge** [comment]
>  I think probably the best option is just to make f_repair use whatever size buffer it's given and reduce the precision.

That sounds nice, but maybe too complex?  If it's relatively simple (and doesn't add too much code size) I'd go for that option.

**Comment by jimmo** [comment]
I've added the one test image. I'd like to create some more interesting ones, will do that in a separate PR.
Updated the bitmap usage as discussed.

**Comment by dpgeorge** [comment]
Looks really good, thanks.  Merged in de6123238e81dc702678ec03f1463f1a6815ad2d and e2e5b56a73f8e99e734d011a2108f147083fcb18

**Pull request closed without merging**
